// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qttaoxsszetewlpobwix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0dGFveHNzemV0ZXdscG9id2l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTM1MjMsImV4cCI6MjA3MDc2OTUyM30.bZ1-_AaSNO4z17FsGFFlu1oEOkoWTYCYjxbPGbIFRN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});